version: '3.8'

services:
  ms1-nestjs:
    build: ./ms1-nestjs
    ports:
      - "3000:3000" # container 内の 3000 番ポートをホストの 3000 番ポートにマッピング
    volumes:
      - ./ms1-nestjs:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: ms1_db
    command: sh -c "npm run migrate && npm run start"
    depends_on:
      ms1-mysql:
        condition: service_healthy
  
  ms1-mysql:
    platform: linux/x86_64
    image: mysql
    container_name: ms1-mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms1_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306" # ms1 の MySQL はホストの 3306 番ポートにマッピング

  ms2-nestjs:
    build: ./ms2-nestjs
    ports:
      - "3001:3000" # container 内の 3000 番ポートをホストの 3001 番ポートにマッピング
    volumes:
      - ./ms2-nestjs:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: ms2_db
    command: sh -c "npm run migrate && npm run start"
    depends_on:
      ms2-mysql:
        condition: service_healthy

  ms2-mysql:
    platform: linux/x86_64
    image: mysql
    container_name: ms2-mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms2_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3307:3306" # ms2 の MySQL はホストの 3307 番ポートにマッピング

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: false
      KAFKA_CLUSTERS_0_NAME: broker1
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker1:9092
      KAFKA_CLUSTERS_1_NAME: broker2
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: broker2:9093
    networks:
      - sample-network
    depends_on:
      broker1:
        condition: service_healthy
      broker2:
        condition: service_healthy
      kafka-initializer:
        condition: service_completed_successfully

  broker1:
    image: &kafka apache/kafka:3.8.0
    ports:
      - "9092:9092"
    volumes:
      - ./docker/broker1:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTNER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://broker1:29092,CONTROLLER://broker1:29093,EXTERNAL://broker1:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker1:29092,EXTERNAL://broker1:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker1:29093,2@broker2:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_OFFSETS_STORAGE: kafka
      KAFKA_LOG_DIRS: /tmp/kafka/logs
      KAFKA_MIN_INSYNC_REPLICAS: 1
      CLUSTER_ID: kafka-cluster
    networks:
      - sample-network
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "broker1:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 10

  broker2:
    image: apache/kafka:3.8.0
    ports:
      - "9093:9092"
    volumes:
      - ./docker/broker1:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTNER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://broker2:29092,CONTROLLER://broker2:29093,EXTERNAL://broker2:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker2:29092,EXTERNAL://broker2:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker1:29093,2@broker2:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_LOG_DIRS: /tmp/kafka/logs
      KAFKA_OFFSETS_STORAGE: kafka
      KAFKA_MIN_INSYNC_REPLICAS: 1
      CLUSTER_ID: kafka-cluster
    networks:
      - sample-network
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "broker1:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 10

  kafka-initializer:
    container_name: kafka-initializer
    image: *kafka
    working_dir: /opt/kafka/bin
    networks:
      - sample-network
    depends_on:
      broker1:
        condition: service_healthy
      broker2:
        condition: service_healthy
    command: >
      /bin/bash -c "
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic __consumer_offsets --replication-factor=2 --partitions=50 --bootstrap-server broker1:9092 &&
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic added-to-cart.reply --replication-factor=2 --partitions=50 --bootstrap-server broker1:9092
      "

networks:
  sample-network:
    driver: bridge