version: '3.8'

services:
  ms1-nestjs:
    build: ./ms1-nestjs
    ports:
      - "3000:3000" # container 内の 3000 番ポートをホストの 3000 番ポートにマッピング
    volumes:
      - ./ms1-nestjs:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: ms1_db
    command: sh -c "npm run migrate && npm run start"
    depends_on:
      ms1-mysql:
        condition: service_healthy
  
  ms1-mysql:
    platform: linux/x86_64
    image: mysql
    container_name: ms1-mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms1_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306" # ms1 の MySQL はホストの 3306 番ポートにマッピング

  ms2-nestjs:
    build: ./ms2-nestjs
    ports:
      - "3001:3000" # container 内の 3000 番ポートをホストの 3001 番ポートにマッピング
    volumes:
      - ./ms2-nestjs:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: ms2_db
    command: sh -c "npm run migrate && npm run start"
    depends_on:
      ms2-mysql:
        condition: service_healthy

  ms2-mysql:
    platform: linux/x86_64
    image: mysql
    container_name: ms2-mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms2_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3307:3306" # ms2 の MySQL はホストの 3307 番ポートにマッピング

  # kafka1:
  #   image: confluentinc/cp-kafka:latest
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #   depends_on:
  #     - zookeeper

  # kafka2:
  #   image: confluentinc/cp-kafka:latest
  #   ports:
  #     - "9093:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 2
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #   depends_on:
  #     - zookeeper

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000